 numpy as np
def sigmoid(x):
  reimportturn 1/(1+np.exp(-x))

x=np.array([0.5,-1.0,2.0])
output=sigmoid(x)
print(output)

In [ ]:

import numpy as np
def relu(x):
    return np.maximum(0, x)

x = np.array([3, -1.0, 2.0])
output = relu(x)
print(output)




[3. 0. 2.]


In [ ]:
import numpy as np

def step_function(x, threshold=0.5):
    return np.where(x <= threshold, 0, 1)

# Example:
x = np.array([0.2, 0.5, 0.7, 1.0])
output = step_function(x)
print(output)


[0 0 1 1]


In [ ]:


import numpy as np


x = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
labels = np.array([0, 0, 0, 1])


weights = np.array([0.5, -0.5])
bias = -0.8





In [ ]:
def step_function(x, threshold=0.5):
    return np.where(x <= threshold, 0, 1)


And gate


In [ ]:


def perceptron(inputs, weights, bias):

    output = np.dot(inputs, weights) + bias
    print("raw output:")
    print (output)

    output = step_function(output,threshold=0)
    return output


output = perceptron(x, weights, bias)
print("Predicted output:", output)
print(" labels:", labels)
loss=np.mean(np.square(output-labels))
print("loss:",loss)


raw output:
[-0.8 -1.3 -0.3 -0.8]
Predicted output: [0 0 0 0]
 labels: [0 0 0 1]
loss: 0.25


In [ ]:



X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]]).T


Y = np.array([[0, 0, 0, 1]])




# Random weights and biases
W1 = np.random.randn(3, 2)   # Layer 1: 3 neurons, 2 inputs
b1 = np.random.randn(3, 1)

W2 = np.random.randn(2, 3)   # Layer 2: 2 neurons, 3 inputs
b2 = np.random.randn(2, 1)

W3 = np.random.randn(1, 2)   # Output layer: 1 neuron, 2 inputs
b3 = np.random.randn(1, 1)

# Forward pass function
def forward_pass(x):
    z1 = np.dot(W1, x) + b1
    a1 = step_function(z1)

    z2 = np.dot(W2, a1) + b2
    a2 = step_function(z2)

    z3 = np.dot(W3, a2) + b3
    y = step_function(z3)

    return a1, a2, y

# Test forward pass for all AND inputs
for i in range(X.shape[1]):
    x_input = X[:, i].reshape(2, 1)
    a1, a2, y = forward_pass(x_input)
    print(f"Input: {X[:, i]} -> Output: {y.flatten()[0]:.4f}")



Input: [0 0] -> Output: 0.0000
Input: [0 1] -> Output: 0.0000
Input: [1 0] -> Output: 0.0000
Input: [1 1] -> Output: 0.0000
